// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_rAXRJ5ihr-8a7eomLSmWb23cPZVqK_E',
    appId: '1:317252165475:web:84d21ff4eaf318f7697d56',
    messagingSenderId: '317252165475',
    projectId: 'yoks-vadnan',
    authDomain: 'yoks-vadnan.firebaseapp.com',
    storageBucket: 'yoks-vadnan.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC38JAC97RMuqoP33Q08Uw1yVG1vgd5KOM',
    appId: '1:317252165475:android:dbde5569072ca0da697d56',
    messagingSenderId: '317252165475',
    projectId: 'yoks-vadnan',
    storageBucket: 'yoks-vadnan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVlGVwiPTm7lbZNQULLktgwSq2QEUd67Y',
    appId: '1:317252165475:ios:93db2ed0542024e9697d56',
    messagingSenderId: '317252165475',
    projectId: 'yoks-vadnan',
    storageBucket: 'yoks-vadnan.appspot.com',
    iosClientId: '317252165475-38is90tcsr5ceg82mkka5rslit2p586a.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVlGVwiPTm7lbZNQULLktgwSq2QEUd67Y',
    appId: '1:317252165475:ios:93db2ed0542024e9697d56',
    messagingSenderId: '317252165475',
    projectId: 'yoks-vadnan',
    storageBucket: 'yoks-vadnan.appspot.com',
    iosClientId: '317252165475-38is90tcsr5ceg82mkka5rslit2p586a.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFirstApp',
  );
}
